replicaCount: 1
frontend:
  image:
    repository: jamiekariuki/crud-app
    tag: "1706439385d24a8ebf4ad7e8fc8efee2ccbef55e"
backend:
  image:
    repository: jamiekariuki/crud-app
    tag: "1706439385d24a8ebf4ad7e8fc8efee2ccbef55e"
